-- A3: columnas personalizables por tablero
-- Ejecutar en el SQL Editor de Supabase.

create table if not exists board_columns (
  id          bigint generated by default as identity primary key,
  board_id    bigint not null references boards(id) on delete cascade,
  user_id     uuid references auth.users(id) on delete cascade,
  name        text not null,
  color       text not null default '#64748b',
  position    integer not null default 0,
  slug        text,
  is_inbox    boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists board_columns_board_id_idx on board_columns (board_id);

create unique index if not exists board_columns_one_inbox_per_board
  on board_columns (board_id) where is_inbox;

alter table tasks add column if not exists column_id bigint references board_columns(id) on delete cascade;

-- Columnas por defecto en tableros existentes (solo si aún no tienen)
insert into board_columns (board_id, user_id, name, color, position, slug, is_inbox)
select b.id, b.user_id, d.name, d.color, d.position, d.slug, d.is_inbox
from boards b
cross join (
  values
    ('Pendiente',   '#64748b', 0, 'backlog',      true),
    ('En progreso', '#eab308', 1, 'in-progress',  false),
    ('Bloqueos',    '#ef4444', 2, 'in-review',    false),
    ('Completada',  '#4ade80', 3, 'completed',    false)
) as d(name, color, position, slug, is_inbox)
where not exists (
  select 1 from board_columns bc where bc.board_id = b.id
);

-- Enlazar tareas existentes por slug de status
update tasks t
set column_id = bc.id
from board_columns bc
where bc.board_id = t.board_id
  and bc.slug is not null
  and bc.slug = t.status
  and t.column_id is null;

-- Tareas huérfanas → inbox del tablero
update tasks t
set column_id = bc.id
from board_columns bc
where bc.board_id = t.board_id
  and bc.is_inbox
  and t.column_id is null;

alter table board_columns enable row level security;

drop policy if exists "columnas de tableros propios" on board_columns;
create policy "columnas de tableros propios" on board_columns
  for all to authenticated
  using (
    exists (
      select 1 from boards b
      where b.id = board_columns.board_id and b.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from boards b
      where b.id = board_columns.board_id and b.user_id = auth.uid()
    )
  );

-- Realtime opcional (misma publication que tasks)
-- alter publication supabase_realtime add table board_columns;
